name: Playwright Tests
on:
  workflow_dispatch:
  workflow_call:

env:
  #Frontend
  PUBLIC_API_URL: "http://localhost:7071/api/actualizarVisitas"
  PUBLIC_API_CHATBOT_URL: "http://localhost:7071/api/obtenerRespuestaChatBot"
  PUBLIC_API_INFRAESTRUCTURE_URL: "http://localhost:7071/api/obtenerInfraestructura"
  PUBLIC_API_SYSTEM_STATUS_URL: "http://localhost:7071/api/obtenerEstadoSistema"
  PUBLIC_API_GET_LOCATIONS_URL: "http://localhost:7071/api/obtenerTraficoGeo"
  PUBLIC_API_REGISTER_LOCATION_URL: "http://localhost:7071/api/registrarTraficoGeo"

  #Backend 
  FUNCTIONS_WORKER_RUNTIME: "node"
  AzureWebJobsFeatures: "EnableWorkerIndexing"
  RESOURCE_GROUP_NAME: "rg-webapp"
  AzureWebJobsStorage: ${{ secrets.AZUREWEBJOBSSTORAGE }}
  COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
  COSMOS_DB_KEY: ${{ secrets.COSMOS_DB_KEY }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  GEMINI_API: ${{ secrets.GEMINI_API }}
  SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  test:
  
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies (Root)
      run: npm ci
    - name: Install dependencies (Webapp)
      run: |
        cd webapp
        npm ci
    - name: Install dependencies (API)
      run: |
        cd api
        npm ci
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C2F9ABB718B24F1B828033AC756B768A }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AEE88C9DB6BD4147A176D36AD2761518 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8DC390769A7343AC85E2AF2796D41C4F }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
